<?php
/**
 * Single product image gallery.
 *
 * @see     https://woocommerce.com/document/template-structure/
 * @package MyTheme\WooCommerce
 * @version 10.5.0
 */

defined('ABSPATH') || exit;

global $product;

if (! $product instanceof WC_Product) {
    return;
}

$featured_image_id = $product->get_image_id();
$gallery_image_ids = $product->get_gallery_image_ids();
$image_ids         = array_values(
    array_filter(
        array_unique(array_filter(array_merge([$featured_image_id], $gallery_image_ids))),
        'wp_attachment_is_image'
    )
);

if (empty($image_ids)) {
    $placeholder_src = wc_placeholder_img_src('woocommerce_single');
    ?>
    <div class="my-theme-product-gallery" data-gallery-initialized="false">
        <div class="my-theme-product-gallery__main">
            <span class="my-theme-product-gallery__main-link">
                <img
                    class="my-theme-product-gallery__main-image"
                    src="<?php echo esc_url($placeholder_src); ?>"
                    alt="<?php echo esc_attr__('Awaiting product image', 'woocommerce'); ?>"
                    width="300"
                    height="300"
                >
            </span>
        </div>
    </div>
    <?php
    return;
}

$initial_image_id = $image_ids[0];
$initial_full_src = wp_get_attachment_image_url($initial_image_id, 'full');
?>
<div class="my-theme-product-gallery" data-gallery-initialized="false">
    <div class="my-theme-product-gallery__main">
        <a
            class="my-theme-product-gallery__main-link"
            href="<?php echo esc_url($initial_full_src); ?>"
        >
            <?php
            // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress.
            echo wp_get_attachment_image(
                $initial_image_id,
                'woocommerce_single',
                false,
                [
                    'class' => 'my-theme-product-gallery__main-image wp-post-image',
                ]
            );
            ?>
        </a>
    </div>

    <div
        class="my-theme-product-gallery__controls"
        data-slider-state="initial"
        style="--visible-thumbnails:<?php echo esc_attr(min(3, count($image_ids))); ?>"
    >
        <button
            class="my-theme-product-gallery__nav my-theme-product-gallery__nav--previous"
            type="button"
            aria-label="<?php echo esc_attr__('Show previous product images', 'my-theme'); ?>"
            hidden
        >
            <svg class="my-theme-product-gallery__nav-icon" width="12" height="8" viewBox="0 0 12 8" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false">
                <path d="M4.5 1L8 4L4.5 7" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
        </button>

        <div class="my-theme-product-gallery__viewport">
            <div class="my-theme-product-gallery__track">
                <?php foreach ($image_ids as $index => $image_id) : ?>
                    <?php
                    $main_image     = wp_get_attachment_image_src($image_id, 'woocommerce_single');
                    $main_srcset    = wp_get_attachment_image_srcset($image_id, 'woocommerce_single');
                    $main_sizes     = wp_get_attachment_image_sizes($image_id, 'woocommerce_single');
                    $full_image     = wp_get_attachment_image_src($image_id, 'full');
                    $attachment_alt = trim(wp_strip_all_tags(get_post_meta($image_id, '_wp_attachment_image_alt', true)));

                    if ('' === $attachment_alt) {
                        $attachment_alt = woocommerce_get_alt_from_product_title_and_position(
                            $product->get_name(),
                            0 === $index,
                            $index - 1
                        );
                    }
                    ?>
                    <button
                        class="my-theme-product-gallery__thumbnail"
                        type="button"
                        aria-label="<?php
                        echo esc_attr(
                            sprintf(
                                /* translators: %d: Product image position. */
                                __('View product image %d', 'my-theme'),
                                $index + 1
                            )
                        );
                        ?>"
                        aria-pressed="<?php echo 0 === $index ? 'true' : 'false'; ?>"
                        data-main-src="<?php echo esc_url($main_image[0]); ?>"
                        data-main-srcset="<?php echo esc_attr($main_srcset ?: ''); ?>"
                        data-main-sizes="<?php echo esc_attr($main_sizes ?: ''); ?>"
                        data-main-width="<?php echo esc_attr($main_image[1]); ?>"
                        data-main-height="<?php echo esc_attr($main_image[2]); ?>"
                        data-full-src="<?php echo esc_url($full_image[0]); ?>"
                        data-image-alt="<?php echo esc_attr($attachment_alt); ?>"
                    >
                        <?php
                        // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress.
                        echo wp_get_attachment_image(
                            $image_id,
                            'woocommerce_gallery_thumbnail',
                            false,
                            [
                                'class' => 'my-theme-product-gallery__thumbnail-image',
                                'alt'   => $attachment_alt,
                            ]
                        );
                        ?>
                    </button>
                <?php endforeach; ?>
            </div>
        </div>

        <button
            class="my-theme-product-gallery__nav my-theme-product-gallery__nav--next"
            type="button"
            aria-label="<?php echo esc_attr__('Show more product images', 'my-theme'); ?>"
            <?php echo count($image_ids) <= 3 ? 'hidden' : ''; ?>
        >
            <svg class="my-theme-product-gallery__nav-icon" width="12" height="8" viewBox="0 0 12 8" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false">
                <path d="M7.5 1L4 4L7.5 7" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
        </button>
    </div>
</div>
